on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h1> Hey contributor, Thanks for raising this issue. One of our maintainers of this project will soo reach out you, Till then Happy Coding :smiley:"
          pr-message: "<h1>Thanks for raising this PR, one of our maintainers will soon reach out to you, Till then Happy coding :smiley:"
